name: makelint
on: [push, workflow_dispatch]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: my-step
        run: |
          make lint
